### PR TITLE
Added Focus Asia Community

### PR DESCRIPTION
**Pull request by ghost**
Hello! I am adding big Slack Community with Asian origins!

### CODE REVIEW

**Comment by ghost** [comment]
hello @tyshgc ! Did you have chance to look at it? :)

**Comment by ghost** [comment]
Hello @tyshgc ! Any progress on that?

**Comment by tyshgc** [comment]
Oh, sorry I was busy last week...
Is this a paid channel?

**Comment by ghost** [comment]
Hello @tyshgc ! Yeah, I have noticed you checked out the site few times already but couldn't get back to me - appreciate your reply. Yes, its paid (we open it up from time to time tho).

**Comment by ghost** [comment]
@tyshgc just to clarify - by "open" you mean "free to join" ?

**Comment by tyshgc** [comment]
Yes, "Open" is "free join".

**Pull request closed without merging**
